<%@ Page Title="" Language="C#" MasterPageFile="~/Gama.Master" AutoEventWireup="true" CodeBehind="eventFunctions.aspx.cs" Inherits="GamaEventMgmt.EventMgmt.eventFunctions" %>

<%@ Register Assembly="obout_Interface" Namespace="Obout.Interface" TagPrefix="cc3" %>
<%@ Register assembly="obout_Grid_NET" namespace="Obout.Grid" tagprefix="cc1" %>
<%@ Register assembly="obout_SuperForm" namespace="Obout.SuperForm" tagprefix="cc2" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="menu" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <ajaxToolkit:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server"></ajaxToolkit:ToolkitScriptManager>

    <div id="dvSystemMessages" class="success" runat="server" visible="false">
        &nbsp;<asp:Label ID="lblDisplayMessages" runat="server" Text="" ></asp:Label>
    </div>
    <div id="dvWarningMessages" class="warning" runat="server" visible="false"><asp:Label ID="lblWarningMessages" runat="server" CssClass="sysInstrMessagesWarning"></asp:Label></div>
    <div id="dvErrorMEssages" class="error" runat="server" visible="false">
        <asp:Label ID="lblInfo" runat="server" Text="" />
    </div>

    <div class="dataLabelDivs"><asp:Label ID="lblEvent" runat="server" Text="Select event to link this function:"></asp:Label></div> &nbsp;
    <div class="dataCaptureDivs"><asp:DropDownList ID="ddlEvents" runat="server" DataSourceID="odsEvents" DataTextField="evt_Name" DataValueField="evt_id"></asp:DropDownList></div>
    <asp:ObjectDataSource ID="odsEvents" runat="server" SelectMethod="getAllEvents" TypeName="Gama.Event"></asp:ObjectDataSource>
    <br />
            
    <div class="dataLabelDivs"><asp:Label ID="lblEvtFuncName" runat="server" Text="Offer Name:"></asp:Label></div>
    <div class="dataCaptureDivs"><asp:TextBox ID="tbxOfferName" runat="server"></asp:TextBox></div>
    <br />
    <div class="dataLabelDivs"><asp:Label ID="lblOfferDesc" runat="server" Text="Description:"></asp:Label></div>
    <div class="dataCaptureDivs"><asp:TextBox ID="tbxOfferDesc" runat="server"></asp:TextBox></div><br />

    <div class="dataLabelDivs"><asp:Label ID="lblSeatsAvailable" runat="server" Text="Seats Available:"></asp:Label></div>
    <div class="dataCaptureDivs"><asp:TextBox ID="tbxNumSeats" runat="server"></asp:TextBox></div>
    <br />
    
    <cc1:Grid ID="gvwEventFunctions" runat="server" AllowRecordSelection="False" DataSourceID="odsEventFunctions" AutoGenerateColumns="False">
        
        <Columns>
            
            <cc1:Column DataField="evt_Name" HeaderText="Event Name" Index="0">
                
            </cc1:Column>
            <cc1:Column DataField="evf_OfferName" HeaderText="Offer Name" Index="2"></cc1:Column>
            <cc1:Column DataField="evf_Desc" HeaderText="Description" Index="3" Width="250" Wrap="True">
            </cc1:Column>
            <cc1:Column DataField="evf_AvailableSeats" HeaderText="Available Seats" Index="4">
            </cc1:Column>
        </Columns>
        <Templates>
            <cc1:GridTemplate runat="server" ID="tplEvtName">
                <Template>
                    <input type="hidden" id="evf_id" />
                    <input type="hidden" id="evt_id" />
                    
                    <cc2:SuperForm ID="SuperForm2" runat="server" 
                            DataSourceID="odsEventFunctions"
                            AutoGenerateRows="false"
                            AutoGenerateInsertButton ="false"
                            AutoGenerateEditButton="false"
                            AutoGenerateDeleteButton="false"                        
                            DataKeyNames="evf_id, evt_id" DefaultMode="Insert" Width="99%">
                        <Fields>
                            <cc2:DropDownListField DataField="evt_Name" HeaderText="Event Name" DataSourceID="odsEvents"></cc2:DropDownListField>
                            <cc2:BoundField DataField="evf_OfferName" HeaderText="Offer Name"></cc2:BoundField>
                            <cc2:BoundField DataField="evf_Desc" HeaderText="Description"></cc2:BoundField>
                            <cc2:BoundField DataField="evf_AvailableSeats" HeaderText="Available Seats"></cc2:BoundField>
                            <cc2:TemplateField>
                                <EditItemTemplate>
                                    <cc3:OboutButton ID="OboutButton1" Text="Save" OnClientClick="Grid1.save(); return false;" Width="75" runat="server"></cc3:OboutButton>
                                    <cc3:OboutButton ID="OboutButton2" Text="Cancel" OnClientClick="Grid1.cancel(); return false;" runat="server"></cc3:OboutButton>
                                </EditItemTemplate>
                            </cc2:TemplateField>
                        </Fields>
                        <FieldSets>
                            <cc2:FieldSetRow>
                                <cc2:FieldSet id="FsEventName" Title="Event Functions" />
                                
                            </cc2:FieldSetRow>
                        </FieldSets>
                    </cc2:SuperForm>
                    
                </Template>
            </cc1:GridTemplate>
        </Templates>
        
    </cc1:Grid>
    
    <asp:ObjectDataSource ID="odsEventFunctions" runat="server" DeleteMethod="deleteEventFunction" InsertMethod="insertEventFunction" SelectMethod="getEventFunctions" TypeName="Gama.Event" UpdateMethod="updateEventFunction">
        <DeleteParameters>
            <asp:Parameter Name="evf_id" Type="String" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="evt_id" Type="String" />
            <asp:Parameter Name="evfSeats" Type="Int32" />
            <asp:Parameter Name="evfOfferName" Type="String" />
            <asp:Parameter Name="evf_desc" Type="String" />
        </InsertParameters>
        <SelectParameters>
            <asp:ControlParameter ControlID="ddlEvents" DefaultValue="" Name="evt_id" PropertyName="SelectedValue" Type="String" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="evf_id" Type="String" />
            <asp:Parameter Name="evt_id" Type="String" />
            <asp:Parameter Name="availableSeats" Type="Int32" />
            <asp:Parameter Name="evfOffername" Type="String" />
            <asp:Parameter Name="evfDesc" Type="String" />
        </UpdateParameters>
    </asp:ObjectDataSource>
    <br />
    <br />
    <asp:Button ID="btnSave" runat="server" Text="Save" OnClick="btnSave_Click" />


    

</asp:Content>
